name: fashion
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.15
  google_fonts: ^6.2.1
  animate_do: ^3.3.4
  flutter_riverpod: ^2.6.1
  easy_localization: ^3.0.7
  shared_preferences: ^2.3.3
  intl: ^0.19.0
  dio: ^5.7.0
  smooth_page_indicator: ^1.2.0+3
  pinput: ^5.0.0
  responsive_navigation_bar: ^5.0.2
  slide_countdown: ^2.0.2
  animated_custom_dropdown: ^3.1.1
  mobkit_dashed_border: ^0.0.7
  flutter_credit_card: ^3.0.7
  coupon_uikit: ^0.2.1
  flutter_rating_bar: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/icons/
    - assets/images/
    - assets/translations/
    - lib/presentation/category_product/view/checkout_payment_view.dart

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

